const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const schemaDir = path.join(repoRoot, 'prisma', 'schema');
const outFile = path.join(repoRoot, 'prisma', 'schema.prisma');

function build() {
  if (!fs.existsSync(schemaDir)) {
    console.error('Schema directory not found:', schemaDir);
    process.exit(1);
  }

  const files = fs.readdirSync(schemaDir).filter((f) => f.endsWith('.prisma'));

  // Prefer base.prisma first if present
  const ordered = [];
  if (files.includes('base.prisma')) ordered.push('base.prisma');
  files.sort();
  for (const f of files) {
    if (f === 'base.prisma') continue;
    ordered.push(f);
  }

  const header = `// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT DIRECTLY\n// Generated from prisma/schema/*.prisma by scripts/merge-prisma.js\n// ${new Date().toISOString()}\n\n`;

  let out = header;
  for (const file of ordered) {
    const p = path.join(schemaDir, file);
    const content = fs.readFileSync(p, 'utf8');
    out += `// --- ${file} ---\n` + content.trim() + '\n\n';
  }

  fs.writeFileSync(outFile, out, 'utf8');
  console.log('Wrote', outFile);
}

if (require.main === module) {
  build();
}

module.exports = { build };
